// Generated by CoffeeScript 1.9.3
(function() {
  var helperProcess, log;

  log = require('./utils')('proc');

  helperProcess = {
    init: function() {
      log('init');
      return process.on('message', this.recv);
    },
    send: function(msg) {
      return process.send(msg);
    },
    recv: function(msg) {
      return log('received', msg);
    }
  };

  helperProcess.init();

}).call(this);
